import React, { useEffect, useState } from 'react';
import api from '../../api/axios';

const RevenueAnalysis = () => {
    const [revData, setRevData] = useState([]);

    useEffect(() => {
        api.get('/admin/accounting/report?type=INCOMING_REVENUE').then(res => setRevData(res.data.logs));
    }, []);

    return (
        <div className="ra-container">
            <style>{`
                .ra-container { padding: 30px; }
                .ra-split { display: grid; grid-template-columns: 2fr 1fr; gap: 30px; }
                .ra-table-card { background: white; border-radius: 12px; border: 1px solid #e5e7eb; padding: 20px; }
                .ra-info-card { background: #111827; color: white; border-radius: 12px; padding: 30px; display: flex; flex-direction: column; justify-content: center; }
                .ra-row { display: flex; justify-content: space-between; padding: 15px 0; border-bottom: 1px solid #f3f4f6; }
                .ra-store-name { font-weight: 700; color: #374151; }
                .ra-amount { color: #059669; font-weight: 700; }
            `}</style>

            <h1 style={{ marginBottom: '25px' }}>Revenue Analysis by Source</h1>
            
            <div className="ra-split">
                <div className="ra-table-card">
                    <div style={{ marginBottom: '20px', fontWeight: '600', color: '#6b7280' }}>Recent Store Commissions</div>
                    {revData.map(r => (
                        <div key={r.id} className="ra-row">
                            <span className="ra-store-name">{r.store_name || 'Network Indirect'}</span>
                            <span className="ra-amount">+{r.credit}</span>
                        </div>
                    ))}
                </div>

                <div className="ra-info-card">
                    <h2 style={{ margin: '0 0 10px 0', color: '#10b981' }}>Top Performer</h2>
                    <p style={{ opacity: 0.8, lineHeight: '1.6' }}>
                        Most of your revenue is currently being generated by <strong>{revData[0]?.store_name || 'N/A'}</strong>. 
                        Consider increasing campaign visibility for this store.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default RevenueAnalysis;